module.exports = {
    title:      `Test Title`,
    author:     `Many good authors`,
    contact:    `Fake info`,
    image:      `test`,
    color:      `Blue`,
    view:       `Private (only me)`,
    length:      `3-14`,
    budget:     `Low`,
    characters: `<3`,
    locations:  `3-6`, 
    concept:    `Short`,
    logLine:    `This is a short log line for testing!`,
    synopsis:   `This is a synopsis for a potential movie or short. It has a very interesting plot twist.`,
}